app:
    build:
        context: ./
        dockerfile: Dockerfile
    image: vortex
    container_name: ${DOCKER_IMAGES_PREFIX}-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
        - vortex
nginx:
    image: nginx:1.23.2-alpine
    container_name: ${DOCKER_IMAGES_PREFIX}-nginx
    restart: unless-stopped
    ports:
        - 8000:80
    volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
        - vortex
db:
    image: mysql:8.0
    container_name: ${DOCKER_IMAGES_PREFIX}-db
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
        - vortex
